### ISSUE TITLE
doc.rs build error on 0.0.10

### ISSUE THREAD

**Issue by jmhodges** [ewilken/hap-rs#24] opened 2020-02-21 02:11 UTC
Looks like doc.rs had a build error while creating the docs for the new 0.0.10.

https://docs.rs/crate/hap/0.0.10/builds/223151

Not sure what the deal is

**Comment by ewilken** [comment] 2020-02-21 13:13
Apparently `"Read-only file system"` when the `build.rs` is modifying the `src` directory? 🤔 Gonna have to look into that.

**Comment by Roba1993** [comment] 2020-08-10 09:06
Has this been fixed with #30 ?
Also the github actions are working again since that merge.
Maybe publish the pre-2 version to crates.io to check.

**Comment by ewilken** [comment] 2020-08-10 11:02
No, unfortunately not. The error is due to the codegen happening in `build.rs` that is modifying the contents of `src`, which seems to be an anti-pattern.

I'm planning on redoing the codegen part using [the `codegenrs` approach](https://epage.github.io/blog/2019/10/speeding-up-rust-builds-code-gen-edition/) as soon as I have time (hopefully tonight).

**Comment by ewilken** [comment] 2020-08-10 19:29
With the latest release, the issue is [fixed now](https://docs.rs/crate/hap/0.1.0-pre.2). So closing this. :-)

**Closed by ewilken** 2020-08-10 19:29 UTC
Labels: bug
